
export const ESTADO_APROBACION =
{
    APROBADO: "APROBADO",
    RECHAZADO: "RECHAZADO",
    PENDIENTE: "PENDIENTE",
}
export const DOCUMENTO =
{
    AUTORIZACION_SANITARIA: "AUTORIZACION_SANITARIA",
    SITUACION_FUNCIONAMIENTO: "SITUACION_FUNCIONAMIENTO",
    NUMERO_REGISTRO: "NUMERO_REGISTRO",
    CERTIFICACIONES: "CERTIFICACIONES",
}
